server:
  port: 8091
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # MySQL 配置
  datasource:
    url: jdbc:mysql://localhost:3306/note_chat?characterEncoding=utf-8&serverTimezone=UTC
    username: # 你的数据库账号
    password: # 你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

minio:
  endpoint: # 你的服务地址
  accessKey: # 你的账号
  secretKey: # 你的密码
  bucket: # 你的桶


file:
  url:
    prefix: # 你的服务地址